Final merge for code review
M-AminAlizadeh/CountriesOfTheWorld pull request #10
Opened 2023-09-07 10:34 UTC by M-AminAlizadeh

The things that I did in this PR:

- Select the API
- Build file structure
- Prepare routes and navigation
- Make sure that a user can display a list of items and filter them. Data should come from the API
- Create the tests for the application
- Style your components to match the design provided.
- Deploy the project and test for final details.
- Record a video for your project.
- Create a good README

2023-09-07 11:16 UTC, julie-ify requested changes
## Hi @M-AminAlizadeh,

Good job so far!

## Highlights!
- Unique routes configuration ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-07 11:16 UTC, julie-ify commented on README.md
> +- [Live Demo Link](https://m-aminalizadeh.github.io/CountriesOfTheWorld/)
- [ ] Your live demo displayed nothing on the page when I visited it. Kindly fix that.

  ![image](https://github.com/M-AminAlizadeh/CountriesOfTheWorld/assets/81468675/63815d90-3d94-4acc-86a0-6af299f01a65)

2023-09-07 11:16 UTC, julie-ify commented on package.json
> +  "homepage": "https://m-aminalizadeh.github.io/CountriesOfTheWorld/",
- [ ] In the local development when your app starts it takes me to `localhost:3000/CountriesOfTheWorld`, which displays nothing because it is not a route. When I remove `/CountriesOfTheWorld/` from here it starts as expected on the homepage you want with the data from the API. Kindly fix this issue.

  ```
  "homepage": "https://m-aminalizadeh.github.io",
  ```

- [ ] **[OPTIONAL]** This could be why your live demo is not working either. I would advise you look into that.

2023-09-07 14:46 UTC, M-AminAlizadeh commented on README.md
> +Please first check this video most of your questions answeres are here :[Video link](https://www.loom.com/share/ee7caa14dfad4eab812c4c4d107cdedb?sid=47e92359-0bf4-400c-bc3d-46ba2ddd7f2c)
@julie-ify you are right
I will make another one and display the codes too

2023-09-08 08:01 UTC, levy002 requested changes
## Hello @M-AminAlizadeh   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 
- You implemented the suggested changes :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 09:00 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @M-AminAlizadeh 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![0bd223a2b156e0eaf61a713e84c3d3b7](https://user-images.githubusercontent.com/57408419/255594021-109e7375-12de-4f5b-9e29-79eefc52e35a.gif)



## To highlight :champagne: 

- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 09:22 UTC, M-AminAlizadeh commented on README.md
@joel-kalema My video includes all of the requirements I think you didn't watch it until the end and I highlighted the codes several times during the video

2023-09-08 09:28 UTC, M-AminAlizadeh commented on README.md
@levy002 Ok

2023-09-08 09:34 UTC, joel-kalema commented on README.md
Hello @M-AminAlizadeh, 
Please  make sure the content of the video includes these 3 points as it is [required](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20content%20of,very%20proud%20of.):
- a description of the project.
- a demo of the project features.
- You should also highlight some interesting piece of code or something you built that you are very proud of.

2023-09-08 09:47 UTC, danmainah requested changes
Hi @M-AminAlizadeh , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️  Implemented the design given and ensured all functionality are working.
✔️  Added tests and ensured all tests are passing


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-08 09:47 UTC, danmainah commented on README.md
> +Please first check this video most of your questions answeres are here :[Video link](https://www.loom.com/share/ccd01f0bb1fd43dda5b16481455325aa?sid=a50c0692-7e29-4412-930a-a20b7537a012)
- [ ] @M-AminAlizadeh Great work on your presentation, however, I think you didn't understand the project requirements,I have tried to explain it below and included a screenshot of all the requirements:

1. A description of the project( what is the project about eg building a Metrics webapp and following the design given)
2.  A demo of the project features( eg homepage , detailed page ,how user can search the country)
3.  Highlight some interesting piece of code or something you built that you are very proud of (kindly remember to use the actual word eg this section am most proud of or this feature was the most interesting section to build during the presentation while showcasing the section)

![image](https://github.com/M-AminAlizadeh/CountriesOfTheWorld/assets/61408860/6bdbfe24-bc2d-4ae0-a9c6-70841e57c7f9)

2023-09-08 10:02 UTC, M-AminAlizadeh commented on README.md
> +Please first check this video most of your questions answeres are here :[Video link](https://www.loom.com/share/ccd01f0bb1fd43dda5b16481455325aa?sid=a50c0692-7e29-4412-930a-a20b7537a012)
@danmainah Thank you very much for the precise explanation of my issues on the video.

2023-09-08 10:33 UTC, merged